- id: asoijeunakaisps
  alias: Melding - Bak buitenzetten
  trigger:
    platform: time
    at: 07:32:00
  condition:
  - condition: template
    value_template: ' {{ (''Gft'' in states.calendar.inzamelkalender_hvc.attributes.message
      or ''Plastic'' in states.calendar.inzamelkalender_hvc.attributes.message) and
      now().strftime(''%D'') == strptime(states.calendar.inzamelkalender_hvc.attributes.start_time,
      ''%Y-%m-%d %H:%M:%S'').strftime(''%D'') }}'
  action:
  - data:
      message: Vergeet je niet de {{ states.calendar.inzamelkalender_hvc.attributes.message
        }} bak buiten te zetten?
    service: notify.signal
- id: asoijeunakaispasdli823
  alias: Melding - Later thuis
  trigger:
    platform: time
    at: '17:15:00'
  condition:
  - condition: state
    entity_id: person.rick
    state: Rick Werk
  - condition: state
    entity_id: person.mayla
    state: home
  action:
  - data:
      message: Rick is later thuis, hij is nu  nog op t werk
    service: notify.signal_mayla
- id: alsdflkyedk
  alias: Iedereen Weg - Lichten Uit
  trigger:
  - entity_id: group.all_devices
    from: home
    platform: state
    to: not_home
  condition:
  - condition: state
    entity_id: light.keuken
    state: 'on'
  - condition: state
    entity_id: light.hoge_tafel
    state: 'on'
  - condition: state
    entity_id: light.lage_tafel
    state: 'on'
  action:
  - data:
      entity_id: scene.woonkamer_uit
    service: scene.turn_on
  - data:
      entity_id: scene.gang_uit
    service: scene.turn_on
- id: oijhfkjdnckasdfjlkjd
  alias: Voordeur hoog
  trigger:
  - entity_id: person.mayla
    from: not_home
    platform: state
    to: home
  - entity_id: person.rick
    from: not_home
    platform: state
    to: home
  action:
  - data:
      entity_id: scene.voordeur_hoog
    service: scene.turn_on
- id: oijhfkjdnckd
  alias: Thuis Komen
  trigger:
  - entity_id: person.mayla
    from: not_home
    platform: state
    to: home
  - entity_id: person.rick
    from: not_home
    platform: state
    to: home
  condition:
  - condition: state
    entity_id: light.keuken
    state: 'off'
  - condition: state
    entity_id: light.hoge_tafel
    state: 'off'
  - condition: state
    entity_id: light.lage_tafel
    state: 'off'
  - condition: state
    entity_id: binary_sensor.chromecast_playing
    state: 'off'
  action:
  - service: script.turn_on
    data:
      entity_id: script.homecoming
  - service: notify.signal
    data:
      message: "Er is iemand thuis gekomen! Ik doe lichten aan :-)"
- id: cancelhomecoming
  alias: Cancel Homecoming AutoOff
  trigger:
  - entity_id: light.gang
    from: 'on'
    platform: state
    to: 'off'
  condition:
  - condition: state
    entity_id: script.homecoming
    state: 'on'
  action:
  - service: script.turn_off
    data:
      entity_id: script.homecoming
- id: voordeurautoturnoff
  alias: Voordeur Auto Laag
  trigger:
  - event_data:
      domain: scene
      service: turn_on
      service_data:
        entity_id: scene.voordeur_hoog
    event_type: call_service
    platform: event
  action:
  - delay: 00:10:00
  - data:
      entity_id: scene.voordeur_laag
    service: scene.turn_on
- id: fiwe8i93kdjf
  alias: Switch scene
  trigger:
  - entity_id: sensor.woonkamer_scene
    platform: state
  - entity_id: light.hoge_tafel
    platform: state
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: light.hoge_tafel
    state: 'on'
  action:
  - data_template:
      entity_id: '{{ states("sensor.woonkamer_scene") }}'
    service: scene.turn_on
- id: poijnjhyt
  alias: Lichten aan bij zonsondergang
  trigger:
  - entity_id: group.in_het_donker
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: group.all_devices
    state: home
  - condition: state
    entity_id: light.hoge_tafel
    state: 'off'
  - condition: state
    entity_id: light.lage_tafel
    state: 'off'
  - condition: state
    entity_id: binary_sensor.chromecast_playing
    state: 'off'
  - after: '12:00:00'
    condition: time
  action:
  - data_template:
      entity_id: '{{ states("sensor.woonkamer_scene") }}'
    service: scene.turn_on
- id: ijiuywekjf
  alias: Buitenverlichting aan bij zonsondergang
  trigger:
  - below: '-3.95'
    entity_id: sun.sun
    platform: numeric_state
    value_template: '{{ state.attributes.elevation }}'
  condition:
  - after: '12:00:00'
    condition: time
  action:
  - data:
      entity_id: scene.buiten_aan
    service: scene.turn_on
- id: qwernmd
  alias: Buitenverlichting uit om 1 uur
  trigger:
    platform: time
    at: 01:00:00
  action:
  - data:
      entity_id: scene.buiten_uit
    service: scene.turn_on
- id: qwueio
  alias: Start Film
  trigger:
  - entity_id: binary_sensor.chromecast_playing_movie
    from: 'off'
    platform: state
    to: 'on'
  action:
  - data:
      entity_id: scene.woonkamer_uit
    service: scene.turn_on
  - data:
      entity_id: scene.buiten_laag
    service: scene.turn_on
  - data:
      entity_id: script.startmovie
    service: script.turn_on 
- id: qiionaluenflsdi
  alias: Start Serie
  trigger:
  - entity_id: binary_sensor.chromecast_playing_tvshow
    from: 'off'
    platform: state
    to: 'on'
  action:
  - data:
      entity_id: scene.woonkamer_donker
    service: scene.turn_on
- id: io8uafj
  alias: Pauze Chromecast
  trigger:
  - entity_id: binary_sensor.chromecast_playing
    from: 'on'
    platform: state
    to: 'off'
  action:
  - data_template:
      entity_id: '{{ states("sensor.woonkamer_scene") }}'
    service: scene.turn_on
  - data:
      entity_id: scene.buiten_aan
    service: scene.turn_on
- id: oiasdflkjasd
  alias: Schakel keuken werklicht in
  trigger:
  - entity_id: light.keuken_medium
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: light.keuken_low
    state: 'on'
  action:
  - data:
      entity_id: switch.keuken_werklicht
    service: switch.turn_on
- id: asdfi3whbfalif39d
  alias: Schakel keuken werklicht uit
  trigger:
  - entity_id: light.keuken_medium
    from: 'on'
    platform: state
    to: 'off'
  condition:
  - condition: state
    entity_id: switch.keuken_werklicht
    state: 'on'
  action:
  - data:
      entity_id: switch.keuken_werklicht
    service: switch.turn_off
- id: kerstboomaan
  alias: Schakel Kerstboom
  trigger:
  - entity_id: light.zithoek
    platform: state
  action:
  - service_template: switch.turn_{{ states("light.zithoek") }} 
    data: 
      entity_id: switch.flexschakelaar_1
- id: huehueheuhue
  alias: Schakel Hue
  trigger:
  - entity_id: light.zithoek
    platform: state
  action:
  - service_template: light.turn_{{ states("light.zithoek") }} 
    data: 
      entity_id:
      - light.huego
      - light.lightstrip_tv
- id: dingdonglicht
  alias: Voordeur hoog na aanbellen
  trigger:
  - entity_id: binary_sensor.deurbel
    from: 'off'
    platform: state
    to: 'on'
  action:
  - data:
      entity_id: scene.voordeur_hoog
    service: scene.turn_on
  - data:
      entity_id: counter.doorbel_today
    service: counter.increment
  - service: media_player.play_media
    data_template:
      entity_id: media_player.google_mini
      media_content_id: http://www.orangefreesounds.com/wp-content/uploads/2015/02/Funny-doorbell-sound-3.mp3
      media_content_type: 'audio/mp3'
  - service: notify.signal
    data:
      message: "Er is aangebeld!"
- id: dingdongfilm
  alias: Film op pauze na aanbellen
  trigger:
  - entity_id: binary_sensor.deurbel
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: binary_sensor.chromecast_playing
    state: 'on'
  action:
  - data:
      entity_id: media_player.woonkamer
    service: media_player.media_pause
- id: inhetdonkeraan
  alias: Automations in het donker aan
  trigger:
  - entity_id: binary_sensor.dusk
    from: 'off'
    platform: state
    to: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: group.in_het_donker
- id: inhetdonkeruit
  alias: Automations in het donker uit
  trigger:
  - entity_id: binary_sensor.dusk
    from: 'on'
    platform: state
    to: 'off'
  action:
    service: homeassistant.turn_off
    entity_id: group.in_het_donker
- id: resetforday
  alias: Reset dagelijkse automations
  trigger:
    platform: time
    at: 01:00:00
  action:
  - data:
      entity_id: counter.doorbel_today
    service: counter.reset
- id: catchall
  alias: Zet alle dingen uit die perongeluk nog aanstaan
  trigger:
    platform: time
    at: '23:00:00'
  action:
  - data:
      entity_id: switch.flexschakelaar_2
    service: switch.turn_off
- id: '1561896723304'
  alias: Lichten uit wanneer licht genoeg
  trigger:
  - entity_id: group.in_het_donker
    from: 'on'
    platform: state
    to: 'off'
  condition:
  - condition: state
    entity_id: light.hoge_taf
    state: 'on'
  - condition: state
    entity_id: light.lage_tafel
    state: 'on'
  action:
  - data:
      entity_id: scene.woonkamer_uit
    service: scene.turn_on
- id: afkuasughef23ihf
  alias: Scene Sensor Update
  trigger:
    - platform: time_pattern
      minutes: '/5'
  action:
  - service: homeassistant.update_entity
    entity_id: sensor.woonkamer_scene
- id: sintemaartenmikmak
  alias: Saint Martens Party
  trigger:
  - entity_id: binary_sensor.deurbel
    from: 'off'
    platform: state
    to: 'on'
  action:
  - service: script.turn_on
    data:
      entity_id: script.sintemaarten
