- platform: template
  sensors:
    dusk:
      friendly_name: "Schemer"
      value_template: >-
        {{ states("sensor.lux_woonkamer")|float < 55 }}
- platform: template
  sensors:
    niceweather:
      friendly_name: "Lekker Weer"
      value_template: >-
        {{ (state_attr('weather.dark_sky','temperature')|float > 18) }}

- platform: template
  sensors:
    chromecast_playing:
      friendly_name: "Chromecast Playing"
      value_template: >-
        {{ is_state('media_player.woonkamer', 'playing') 
            and (state_attr('media_player.woonkamer','app_name') in ["Netflix","Pathé Thuis","Disney+"]
            or state_attr('media_player.woonkamer','app_name') in ["Plex"]
            and state_attr('media_player.woonkamer','media_content_type') in ["movie","tvshow"]) }}

- platform: template
  sensors:
    chromecast_playing_movie:
      friendly_name: "Chromecast Playing Movie"
      value_template: >-
        {{ is_state('media_player.woonkamer', 'playing') 
            and (state_attr('media_player.woonkamer','app_name') in ["Netflix","Pathé Thuis","Disney+"]
            or state_attr('media_player.woonkamer','app_name') in ["Plex"]
            and state_attr('media_player.woonkamer','media_content_type') in ["movie"]) }}

- platform: template
  sensors:
    chromecast_playing_tvshow:
      friendly_name: "Chromecast Playing TV Show"
      value_template: >-
        {{ is_state('media_player.woonkamer', 'playing') 
            and state_attr('media_player.woonkamer','app_name') in ["Plex"]
            and state_attr('media_player.woonkamer','media_content_type') in ["movie"] }}

- platform: workday
  country: NL
  workdays: [mon, tue, wed, thu, fri]
