homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 1
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

# Enables System Health
system_health:

# Enables the frontend
frontend:

# Enables homekit

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
# updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Log events into InfluxDB
influxdb:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Ikea Tradfri
tradfri:
  host: !secret tradfri_host
  allow_tradfri_groups: false

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

# Life360 Activity Tracker
device_tracker:
  - platform: ping
    consider_home: 30
    hosts:
      phone_mayla: 192.168.0.120
      phone_rick: 192.168.0.121

life360:
  accounts:
    - username: !secret life360_user
      password: !secret life360_password
  members:
    include:
      - Rick Mettes
      - Mayla

person:
  - name: Mayla
    id: mayla
    device_trackers:
      - device_tracker.phone_mayla
      - device_tracker.life360_mayla
  - name: Rick
    id: rick
    device_trackers:
      - device_tracker.phone_rick
      - device_tracker.life360_rick_mettes

# MessageBird
notify:
  - name: SMS
    platform: message_bird
    api_key: !secret messagebird_apikey
    sender: Dobby

counter:
  doorbel_today:
    name: Deurbelletjes Vandaag
    icon: mdi:bell-ring-outline
    restore: false
    initial: 0
    step: 1

# DarkSky
weather:
  - platform: darksky
    api_key: !secret darksky_api_key 

# Chromecast
cast:
  media_player:
    - host: !secret chromecast_woonkamer_ip
    - host: !secret jbl_speaker_ip

# Google
google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

# Ecovacs
# ecovacs:
#  username: !secret ecovacs_username
#  password: !secret ecovacs_password
#  country: !secret ecovacs_country
#  continent: !secret ecovacs_continent

light: !include light_groups.yaml
sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
zone: !include zones.yaml
