- platform: pi_hole
  host: pi.hole
- platform: history_stats
  name: Rick at Home
  entity_id: device_tracker.rick_mettes
  state: 'home'
  type: ratio
  end: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  duration:
    days: 7
- platform: history_stats
  name: Rick at Work
  entity_id: device_tracker.rick_mettes
  state: 'Rick Werk'
  type: ratio
  end: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  duration:
    days: 7
- platform: history_stats
  name: Mayla at Home
  entity_id: device_tracker.mayla_
  state: 'home'
  type: ratio
  end: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  duration:
    days: 7
- platform: history_stats
  name: Mayla at Work
  entity_id: device_tracker.mayla_
  state: 'Mayla Werk'
  type: ratio
  end: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  duration:
    days: 7
- platform: history_stats
  name: Lights Woonkamer on
  entity_id: group.woonkamer
  state: 'on'
  type: time
  end: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  duration:
    days: 7
- platform: template
  sensors:
    dusk:
      friendly_name: "Schemer"
      value_template: >-
        {% if not is_state('weather.dark_sky', 'clear') %}
          {% if states.sun.sun.attributes.elevation|float < 7 %}
            yes
          {% else %}
            no
          {% endif %}
        {% else %}
          {% if states.sun.sun.attributes.elevation|float < 3.5 %}
            yes
          {% else %}
            no
          {% endif %}
        {% endif %}

    chromecast_movie:
      friendly_name: "Chromecast Playing Movie"
      value_template: >-
        {% if is_state('media_player.woonkamer', 'playing') %}
          {% if states.media_player.woonkamer.attributes.app_name  in ["Plex","Netflix","Pathé Thuis"] %}
            {% if states.media_player.woonkamer.attributes.media_content_type  in ["movie"] or states.media_player.woonkamer.attributes.app_name  in ["Netflix","Pathé huis"] %}
              yes
            {% else %}
              no
            {% endif %}
          {% else %}
            no
          {% endif %}
        {% else %}
          no
        {% endif %}

    chromecast_tvshow:
      friendly_name: "Chromecast Playing TV Show"
      value_template: >-
        {% if is_state('media_player.woonkamer', 'playing') %}
          {% if states.media_player.woonkamer.attributes.app_name  in ["Plex","Netflix","Pathé Thuis"] %}
            {% if states.media_player.woonkamer.attributes.media_content_type  in ["tvshow"] %}
              yes
            {% else %}
              no
            {% endif %}
          {% else %}
            no
          {% endif %}
        {% else %}
          no
        {% endif %}

