title: My Awesome Home

resources:
  - url: /local/mini-graph-card.js
    type: module

views:
    # View tab title.
  - title: Example
    # Define cards
    cards:
    - type: map
      entities:
        - device_tracker.rick_mettes
        - device_tracker.mayla_
        - zone.klimhal
        - zone.rick_werk
        - zone.mayla_werk
        - zone.crossfit
    - type: weather-forecast
      entity: weather.dark_sky
    - type: horizontal-stack
      cards:
      - type: entity-button
        name: Woonkamer gedimd
        entity: scene.woonkamer_gedimd
        service: scene.turn_on
      - type: entity-button
        name: Woonkamer uit
        entity: scene.woonkamer_uit
        service: scene.turn_on
    - type: media-control
      entity: media_player.woonkamer
    - type: gauge
      entity: sensor.mayla_at_home
      title: Mayla thuis
      unit_of_measurement: '%'
    - type: gauge
      entity: sensor.mayla_at_work
      title: Mayla op t werk
      unit_of_measurement: '%'
    - type: gauge
      entity: sensor.rick_at_home
      title: Rick thuis
      unit_of_measurement: '%'
    - type: gauge
      entity: sensor.rick_at_work
      title: Rick op t werk
      unit_of_measurement: '%'
    - type: gauge
      entity: sensor.lights_woonkamer_on
      title: Woonkamer lichten aan
      unit_of_measurement: 'Uur'
